### PR TITLE
Add internal DiscordRole constructor

### PR DESCRIPTION
**Pull request by armaa**
As said in the title, having a public (or rather default..) `DiscordRole` constructor is obsolete because theres no way to make a new role out of it, as in add/remove permissions to the object itself, and every other entity has this sort of thing to prevent the user to create a new object which isnt possible to edit then in any way, since most of them (if not all) just have getters and no methods to edit/add/remove stuff.

### CODE REVIEW

**Comment by Emzi0767** [comment]
Move the constructor below the properties and I'll merge.

**Comment by armaa** [comment]
Below `Mention` as well?

**Comment by moonPtr** [comment]
Below `Mention`, since it's a-

mfw commit happens in the middle of me typing comment

**Comment by armaa** [comment]
Yeah, i figured its seperated in a way of `json properties | other invokable stuff` so i put it there at first.. I understand now

**Pull request merged**
