### PR TITLE
[ci skip] fix spacing issue in Readme

### PR DESCRIPTION
**Pull request by uwx**
:^)

this improves:
- accessibility
- SEO
- W3C standards compliance

### CODE REVIEW

**Comment by NaamloosDT** [comment]
https://ping-b1nzy.today/afd33e.png

:^):^)

**Comment by Emzi0767** [comment]
This makes me mad.

**Comment by uwx** [comment]
starving kids in africa could be eating that wasted byte!

**Comment by Emzi0767** [comment]
*grumble grumble*

**Pull request merged**
