### PR TITLE
[WIP] Split *.ModifyAsync into smaller methods

### PR DESCRIPTION
**Pull request by uwx**
# Summary
Takes the concept from #206 (and #207) and applies it to all ModifyAsync methods.

# Details
This takes the ModifyAsync methods and breaks them down into smaller methods for each argument.

# Changes proposed
* Split DiscordWebhook.ModifyAsync into smaller methods (d5d9c64)
* Split DiscordChannel.ModifyAsync into smaller methods (ce314c4)
* Split DiscordMember.ModifyAsync into smaller methods (58975d5)
* Split DiscordGuildEmoji.ModifyAsync into smaller methods (d7f94fb)
* Split DiscordGuild.ModifyAsync into smaller methods (7ac68af)

### CODE REVIEW

**Comment by NaamloosDT** [comment]
please resolve the the build error and fill out the contribution form

**Comment by uwx** [comment]
gee i wonder what the WIP in the title means 🙄

**Comment by moonPtr** [comment]
Buy CI lootboxes today to get a chance of your build succeeding

**Comment by NaamloosDT** [comment]
Missed that

**Comment by Emzi0767** [comment]
I'm not for that. The creation methods were ok, because of the argument count. This is too much.

**Comment by uwx** [comment]
"Too much" is to have a method with _13 fucking arguments._

**Comment by Emzi0767** [comment]
Blame Discord. Splitting a single operation into several is not OK. If it was an alias that simply prevents confusion, it'd be fine. If it's a single operation, multiple data, they should not be split.

**Comment by uwx** [comment]
That's a bad excuse

**Comment by Emzi0767** [comment]
It's not an excuse, it's a fact.

**Comment by uwx** [comment]
_[the sound of ¯\\\_(ツ)\_/¯ echoes through the abyss]_

**Comment by Emzi0767** [comment]
An alternative would be introducing ASP.NET Core-like model overloads which take a model callback thing, akin to what D.NET does, so you can have (in addition to what's already available):

```cs
channel.ModifyAsync(x =>
{
    x.Name = "newname";
    x.Topic = "New Topic";
});
```

Etc. We've been considering something like that around 2.x development, but ultimately decided it was too much effort to implement at the time, and then we just forgot about the idea.

If you feel like up to the task, I would welcome that. Note that I'd like that *in addition* to existing methods.

The kind of problem you'd be facing is handling the models in a clean manner (as it would require you to introduce a bunch of new types, preferably in the `DSharpPlus.Net.Abstractions` namespace).

**Pull request closed without merging**
