### PR TITLE
[ci skip] Fixed missing . causing formatting issue

### PR DESCRIPTION
**Pull request by iDerp**

### CODE REVIEW

**Comment by uwx** [comment]
LGTM

**Comment by iDerp** [comment]
Before it looked like this
Thonk

**Comment by NaamloosDT** [comment]
https://ping-b1nzy.today/afd33e.png
kek good luck

**Comment by NaamloosDT** [comment]
oh that was about single character PRs in general :^)

**Comment by NaamloosDT** [comment]
oh
fuck

(ignore me it's late)

**Pull request merged**
