### PR TITLE
mark CooldownBucketType as Flags enum

### PR DESCRIPTION
**Pull request by uwx**
# Summary
Adds the Flags attribute to CooldownBucketType.

# Details
Bitwise operations are performed on CooldownBucketType, but it's not marked with the Flags attribute. God forbid this fixes a ReSharper issue.

# Changes proposed
* Add the Flags attribute to CooldownBucketType.

### CODE REVIEW

**Comment by Emzi0767** [comment]
It's not meant to be used that way.

**Comment by uwx** [comment]
B-b-but you're doing bitwise operations on it, Emzi-sama!~~

**Comment by Emzi0767** [comment]
Even if, all that it does is just changing how `.ToString()` works.

**Comment by uwx** [comment]
Well it's more a syntax change than a functionality change.

**Pull request closed without merging**
